package core.worker;

public enum WorkerOperations {
	ACQUIT_OR_CHARGE_ACCOUNT,
	CANCEL_CUSTOMER_ORDER,
	INITIALIZE_PARKING_LOT,
	PARKING_LOT_FULL,
	RESERVE_PARKING_SPACE,
	OUT_OF_ORDER,
	UPDATE_RATES,
	DECIDE_ON_RATES,
	DECIDE_ON_COMPLAINTS,
	CHANGE_PARKING_LOT,
	OUT_OF_ORDER_REPORT,
	ORDERS_REPORT,
	COMPLAINTS_REPORT,
	LOT_SPACES_REPORT,
	CURRENT_SUBSCRIBERS_REPORT,
	OPERATIONS_REPORT,
	PERFORMENCE_REPORT,
}
