package core.worker;

public enum WorkerRequestType {
	ACQUIT_OR_CHARGE_ACCOUNT,
	CANCEL_CUSTOMER_ORDER,
	INITIALIZE_PARKING_LOT,
	PARKING_LOT_FULL,
	RESERVE_PARKING_SPACE,
	OUT_OF_ORDER,
	UPDATE_RATES,
	REQUEST_COMPLAINTS_FOR_REVIEW,
	REQUEST_RATES_FOR_REVIEW,
	DECIDE_ON_RATES,
	DECIDE_ON_COMPLAINTS,
	PARKING_LOT_NAMES,
	REQUEST_PERMISSIONS,
	PARKING_LOT_INFO,
	BAD_REQUEST, // Used only for responses. The client should not send this request
	OUT_OF_ORDER_REPORT,
	ORDERS_REPORT,
	COMPLAINTS_REPORT,
	LOT_SPACES_REPORT,
	CURRENT_SUBSCRIBERS_REPORT,
	OPERATIONS_REPORT,
	PERFORMENCE_REPORT,
}
