package core;

public enum WebCustomerRequestType {
	ORDER_ONE_TIME_PARKING,
	CANCEL_ORDER,
	TRACK_ORDER_STATUS,
	ORDER_ROUTINE_MONTHLY_SUBSCRIPTION,
	ORDER_FULL_MONTHLY_SUBSCRIPTION,
	SUBSCRIPTION_RENEWAL,
	OPEN_COMPLAINT,
// Add more types if required
}
